### ISSUE TITLE
json的问题

### ISSUE THREAD

**Issue by lth2015** [maxwell92/k8sapi#1]
不能decode到deployment对象，原因“可能”有一下几点：
1.  kind没有写
2.  缺metadata.name字段
3.  sepc.selector 不能为空
4.  sepc.template.metadata.labels不能为空
5.  sepc.selector 必须匹配template的'labels'
6.  spec.template.spec.containers不能为空

下面是程序报错：
Could not create deployment: err=Deployment.extensions "" is invalid: [metadata.name: Required value: name or generateName is required, spec.selector: Required value, spec.template.metadata.labels: Invalid value: null: `selector` does not match template `labels`, spec.template.spec.containers: Required value]

程序片段：

``` golang
        _, err = c.Extensions().Deployments(api.NamespaceDefault).Create(deployment)

    if err != nil {
        logger.Fatalf("Could not create deployment: err=%s\n", err)
    }

    logger.Printf("Deployment was created!")
`
```

**Comment by maxwell92** [comment]
Sorry I didn't really get to you in the afternoon. 

This struct is not absolutely same with the Kubernetes deployment struct. It's can't be decoded into Kubernetes struct. Kind, Name, Labels, Containers is a must if you want to post the json to Kubernetes successfully. Selector isn't.

**Comment by maxwell92** [comment]
There still need a struct transmission(AppDeployment -> Deployment) in the backend server.  

You can try your program referring to this [json](https://github.com/maxwell92/k8sapi/blob/master/deploy-test/app-template-test.json)
it's Kubernetes oriented.
